### ISSUE TITLE
Black screen at boot

### ISSUE THREAD

**Issue by julianCast** [guysoft/MagicMirrorOS#10]
After this line, the screen is black.

![photo5933494695655223800](https://user-images.githubusercontent.com/559677/82761989-9a0cb700-9dfe-11ea-81ed-38624079ae4c.jpg)

**Comment by julianCast** [comment]
False alarm, first installation, took a while, patience!

**Comment by khassel** [comment]
you are right, this takes a while, because at the first start the needed docker image is pulled. This needs some minutes depending on your hardware ...

@guysoft may we should mention this in the README.md, may [here](https://github.com/guysoft/MagicMirrorOS#how-to-use-it)?
