### ISSUE TITLE
How to see the logs?

### ISSUE THREAD

**Issue by julianCast** [guysoft/MagicMirrorOS#11]
Before magicMirrorOS, the `npm start` command would show us the log. 
How can we achieve that now with magicMirrorOS? It's useful to debug issues with modules.

Thanks!

**Comment by guysoft** [comment]
This should give you the logs:
```
sudo docker logs mm 
```

**Comment by khassel** [comment]
see also https://gitlab.com/khassel/magicmirror#start-magicmirror

**Comment by guysoft** [comment]
@khassel I suggest you add that to the ``README.md`` here.

**Comment by khassel** [comment]
we may should add something which describes the setup (MagicMirrorOS using docker setup) and then post a link to the readme of the docker setup. Would this be fine for you? I don't want to write the content twice, here and in my docker setup ...
