### ISSUE TITLE
how to install more modules?

### ISSUE THREAD

**Issue by tung256** [guysoft/MagicMirrorOS#15]
i would like to install this quotes module: https://github.com/salpar/MagicMirror-QuoteCatalog/
i followed the instruction but i got an error when i ran this command: npm install
**-bash: npm: command not found**
any idea?

**Comment by guysoft** [comment]
MagicMirror is installed using a docker container docs are here:  https://gitlab.com/khassel/magicmirror
@khassel have any input on this?

**Comment by khassel** [comment]
From the README.md of  https://gitlab.com/khassel/magicmirror:

> There is one difference installing or updating modules compared to a standard setup: You must do the git clone ..., git pull and npm install commands from inside the running docker container. For this you execute docker exec -it mm bash and in this shell you navigate to the modules/MMM-... folder. For exiting from the container you type exit.

**Comment by khassel** [comment]
I'm closing this issue for now. If you think this issue should remain open, please let me know.
