### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by mwkrieger** [guysoft/MagicMirrorOS#18]
I'm having trouble setting the correct timezone in the docker environment. 

The Pi has the correct timezone, but when things boot up to MM, the timezone is incorrect and I can't seem to override it with the correct (US/Eastern) timezone. 

Has anyone got a workaround?

**Comment by khassel** [comment]
Yes, there is some documentation missing about that ...

You have to edit `~/magicmirror/run/docker-compose.yml` and assign the right value to `TZ: Europe/Berlin`.
Then restart mm: Go to `~/magicmirror/run` and execute `docker-compose up -d`.

**Comment by mwkrieger** [comment]
Thank you! That did the trick.

**Comment by khassel** [comment]
I'm closing this issue for now. If you feel this issue should remain open, please let me know.
