### ISSUE TITLE
blank screen on fresh Installation

### ISSUE THREAD

**Issue by beny18241** [guysoft/MagicMirrorOS#20]
Hi,

I've rebooted my raspberry pi 3 with installed MM os yesterday, after that and it's booting with blank screen (Through the web and on MM itself) . I've done a couple of checks and I couldn't find any meaningful info in the logs. So I've reinstalled from scratch ...

.. And the same blank screen on fresh installation on raspberry pi 3,

mm: v2.13.0

#using MagicMirrorOS installation

**Comment by khassel** [comment]
Can reproduce this, but at the moment I have no idea whats happening ...

To get your system running again you can use the `v2.12.0` of the image.
You have to edit `~/magicmirror/run/docker-compose.yml` and replace `image: karsten13/magicmirror:latest` with `image: karsten13/magicmirror:v2.12.0`. 

Then goto `~/magicmirror/run/` and execute `docker-compose up -d`. This will pull the image and then start the mirror in version 2.12.

This is only a workaround, I will come back with a "real" solution.

**Comment by khassel** [comment]
So I found the bug and built a new docker image.

If you already applied the above patch please revert this fist.

Then you can restart your pi (so the new image will be pulled automatically) 

**or** 

goto  `~/magicmirror/run/` and execute 
```bash
docker-compose pull
docker-compose up -d
```

**Comment by beny18241** [comment]
ok, got that - works ! :)
