### ISSUE TITLE
Is it working for Pi Zero W?

### ISSUE THREAD

**Issue by DamienFoulon** [guysoft/MagicMirrorOS#23]
Hey guys !

Is it working on a Pi Zero Wireless ? 
I would create one for my gf and I have an old Pi Zero W in stock so... Maybe it could be use to ^^

**Comment by khassel** [comment]
from the readme:
> Pi 2, 3 & 4. The Raspberry Pi 0/1 is currently not supported.

This means not that its impossible, but ...
- MagicMirror does not support Pi 0/1. The used electron version is not compatible with arm6
- no idea if docker works, if it works it will be very very slow
- no idea if this MagicMirrorOS works on Pi 0/1, may @guysoft can answer this question

**Comment by khassel** [comment]
I'm closing this issue for now. If you feel this issue should remain open, please let me know.
