### ISSUE TITLE
I'm thoroughly confused, how do you run MMPM?

### ISSUE THREAD

**Issue by austinthetaco** [guysoft/MagicMirrorOS#27]
When I ssh in, i see the MMPM in the run/ folder under rpi_mmpm.yml, but it doesn't appear to be running, and typing the "mmpm" command doesn't do anything either. Am i missing something basic here?

**Comment by guysoft** [comment]
Its running using docker as written in the README here.

**Comment by khassel** [comment]
You can run mmpm as docker container (magicmirror runs as docker container too).

For this you must replace the current `docker-compose.yml` in `~/magicmirror/run` with the content of `rpi_mmpm.yml`, e.g. you can `cd` into `~/magicmirror/run` and execute `cp rpi_mmpm.yml docker-compose.yml`.

After this execute `docker-compose up -d` in the same folder. It will take some time to download the mmpm image. After starting the MMPM-GUI is available under `<your-ip>:7890`.

**Comment by guysoft** [comment]
Might be worth adding this to the README

**Comment by khassel** [comment]
Thats already documented in the [docker setup of mmpm](https://gitlab.com/khassel/mmpm).

**Comment by austinthetaco** [comment]
> Thats already documented in the [docker setup of mmpm](https://gitlab.com/khassel/mmpm).

Which obviously makes it unclear in this repo. someone shouldn't need to go to the docker container docs to understand a feature in the code repo
