### ISSUE TITLE
check screensaver and wlan power off

### ISSUE THREAD

**Issue by khassel** [guysoft/MagicMirrorOS#3]
- [x] https://www.raspberrypi.org/documentation/configuration/screensaver.md

- [x] https://www.kuerbis.org/2016/03/raspberry-pi-3-kurztipps-wlan-sleep-mode-verhindern/

**Comment by khassel** [comment]
@guysoft thanks for [this info](https://github.com/guysoft/MagicMirrorOS/issues/4#issuecomment-625086109).

So wlan power save is remaining. This is enabled by default:
````
pi@magicmirroros:~ $ iw wlan0 get power_save
Power save: on
````

I'm not sure if this can lead to a black screen.
We can wait if someone reports this or we can add `sudo iw wlan0 set power_save on` in the start script `run_magicmirroros`. Please let me know ...

**Comment by guysoft** [comment]
take a look at this. The last non upvoted on about the interfaces file:
https://raspberrypi.stackexchange.com/questions/96606/make-iw-wlan0-set-power-save-off-permanent

**Comment by khassel** [comment]
checked this link already, but failed to get this working.

Solutions working are
* `sudo iw wlan0 set power_save off` in `run_magicmirroros`
* `/sbin/iw wlan0 set power_save off` in `/etc/rc.local`
