### ISSUE TITLE
not full screen

### ISSUE THREAD

**Issue by IcyFeather233** [guysoft/MagicMirrorOS#31]
My magic mirror can be displayed normally, but it is not displayed in full screen when it is displayed, I want to know how to make it display in full screen

**Comment by guysoft** [comment]
This might solve your issue:
http://martinpennock.com/blog/how-to-remove-black-border-from-raspberry-pi-display/

**Comment by IcyFeather233** [comment]
Thanks!

**Comment by guysoft** [comment]
Update if it works for you, could be added to README or WIKI

**Comment by IcyFeather233** [comment]
Sorry I don’t know if this is useful or not, because I found that my problem is that the display mode of the screen is not selected correctly. I adjusted the display to the full screen display mode and it works.

**Comment by guysoft** [comment]
Ok, closing for now. If anyone else has the issue too we can add it to the docs.
