### ISSUE TITLE
Perhaps sits time for a new build with latest Rpi image

### ISSUE THREAD

**Issue by guysoft** [guysoft/MagicMirrorOS#32]
@khassel Should we make a new release?

**Comment by khassel** [comment]
The mm stuff is regularly updated. Concerning the OS the latest release is very old.

**Comment by guysoft** [comment]
Ok, had to update the docker module, it builds, here is a new nightly:
http://unofficialpi.org/Distros/MagicMirrorOS/nightly/2021-04-12_2021-03-04-magicmirroros-buster-armhf-lite-0.2.0.zip

md5:
[b02fd691d639c7907c602aaf50d24873](http://unofficialpi.org/Distros/MagicMirrorOS/nightly/2021-04-12_2021-03-04-magicmirroros-buster-armhf-lite-0.2.0.zip.md5)

**Comment by khassel** [comment]
tested the new nightly and pushed a small typo fix to `devel`. So from my side you can trigger a new release with the updated `devel`.

**Comment by guysoft** [comment]
That fix requires triggering a new build. So will do that and put it out as an Release Candidate.

**Comment by guysoft** [comment]
See #34
