### ISSUE TITLE
MagicMirrorOS 0.2.0 RC1 Status 

### ISSUE THREAD

**Issue by guysoft** [guysoft/MagicMirrorOS#34]
An update for the image. Manily so the Firmware shipped is updated and should work with newer Pis.

Changes:
* RpiOS 2021-03-04
* Packages and system have been updated to latest versions

Download:
https://unofficialpi.org/Distros/MagicMirrorOS/nightly/2021-04-13_2021-03-04-magicmirroros-buster-armhf-lite-0.2.0.zip

md5: [5021bb98296a637334846a479472c306](
https://unofficialpi.org/Distros/MagicMirrorOS/nightly/2021-04-13_2021-03-04-magicmirroros-buster-armhf-lite-0.2.0.zip.md5)

**Comment by guysoft** [comment]
@khassel Been two weeks. any chance you or anyone else can confirm this works?
I don't have the hardware. It seems like about 18% of the current users are using version 0.2.0 of some sort, though it might be older nightlies.

**Comment by I4T2B** [comment]
I can test the Image in the next few days. I use one 0.2.0 Image but i have downloaded it about two months ago, is it the same?

**Comment by khassel** [comment]
[this](https://github.com/guysoft/MagicMirrorOS/issues/32#issuecomment-818275365) was my last test.

**Comment by guysoft** [comment]
@khassel there is a new image out that should fix the typo.

@I4T2B Its not.the same image.

**Comment by khassel** [comment]
tested the new image, it works and the typo is fixed.

**Comment by guysoft** [comment]
Released
https://github.com/guysoft/MagicMirrorOS/releases/tag/0.2.0
