### ISSUE TITLE
MMPM_MAGICMIRROR_ROOT has wrong value

### ISSUE THREAD

**Issue by 68267a** [guysoft/MagicMirrorOS#35]
I installed MMOS a few weeks ago and did nothing with it, so I don't remember anything other than "it should be default". 
I think I used the serveronly_mmpm.yml config, so I can browse to :8080 and get a default config. If I go to :7890, the page loads but it gives me a `502 Bad Gateway` popup and it doesn't know what modules are installed (none).

Looking at `docker logs mmpm` I see it can't find the root directory. :7890 shows MMPM_MAGICMIRROR_ROOT:/root/MagicMirror, even though `mmpm --env` has the correct value.

Also I landed here somehow: https://gitlab.com/khassel/mmpm
>  The Control Center of MMPM is not supported. 

Did I miss something? Should I be using the mmpm container? I'm fairly technical but I'm not familiar with the components being used here.

**Comment by khassel** [comment]
This is unrelated to MagicMirrorOS.

I can reproduce this on a fresh install. The first 2 values of the folllowing file you have to set manually, you can do this in the WebUI of MMPM in the tab "config editor", selecting "mmpm-env.json" from the files icon.

```json
{
  "MMPM_MAGICMIRROR_ROOT": "/home/node/MagicMirror",
  "MMPM_MAGICMIRROR_URI": "http://192.168.0.165:8080",
  "MMPM_MAGICMIRROR_PM2_PROCESS_NAME": "",
  "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": "",
  "MMPM_IS_DOCKER_IMAGE": true
}
```

In `MMPM_MAGICMIRROR_URI` you have to use your ip address of the pi.

After this the error is gone, but the active modules page is still not working (have no solution for this at the moment).

Will update the documentation of the mmpm repo and add `"MMPM_MAGICMIRROR_ROOT": "/home/node/MagicMirror",` as default.

**Comment by khassel** [comment]
Updated the docker mmpm setup and the active module page is now working (on my pi3). With a fresh install the `MMPM_MAGICMIRROR_ROOT` is now set to `/home/node/MagicMirror`.

**Comment by khassel** [comment]
I think this is solved, feel free to reopen if not.
