### ISSUE TITLE
Update MagicMirrorOS to latest firmware and updates and add MMPM to install

### ISSUE THREAD

**Issue by Wolfieeewolf** [guysoft/MagicMirrorOS#38]
Recently installed the latest MagicMirrorOS download off the repository. I also tried to install Magic Mirror packager manager(MMPM) and ran into a few issues. I decided maybe an update of some core package might fix things. 

 I did an "apt-get update", "apt-get full-upgrade"  this installed 55 updates. I then thought well might as well update everything so I ran "rpi-update" and update it to the latest firmware. The version installed was 5.10.17-v7+. It is now 5.10.39+. 

I finally was able to get MMPM to install but for some reason, it will not install the modules in the correct folders. I think this is an MMPM issue, not MagicMirrorOS. From what I can see MMPM thinks the install folder of Magic Mirror is "/home/pi/MagicMirror". The MagicMirrorOS install the program in "/home/pi/magicmirror".  I have tried changing this in the MMPM setup but it still will not play the game.

If somehow you can add the updates and MMPM to the OS install I think it would save a lot of time and I can get straight to the configuring instead of having to update and mess about with things.

**Comment by guysoft** [comment]
What version?  0.1.0 or 0.2.0?

**Comment by Wolfieeewolf** [comment]
> 
> 
> What version? 0.1.0 or 0.2.0?

Hey, sorry for the delay

using version  2021-04-13_2021-03-04-magicmirroros-buster-armhf-lite-0.2.0.zip.

I am using a raspberry pi 3 B+

haven't used my Pi for anything in a few years so it could be that I'm just a bit rusty and have missed something with the install process . Haven't had much time to mess about with it so most probably user error at my end

**Comment by Wolfieeewolf** [comment]
I see there is a 0.3.0 version in the nightly builds. will give that a go and see if that works better.  I'll let you know if I have any issues

**Comment by guysoft** [comment]
Yep, I sent that to build when you opened the issue. Update if it fixes it, if so I can even put it as an RC and release it.

**Comment by Wolfieeewolf** [comment]
Did a full update and the firmware is still out of date and apt-get full-upgrade still grabbing some packages but didn't take too long to update it.  Your package works fine and didn't get any errors so I would say your good to release it.

I am still having some issues with MMPM and getting it to install the modules in the correct folders though. Trying to install it as a docker. I have followeded the instructions but I think I'm doing something wrong somewhere. I'm sure I'll work it out.

**Comment by guysoft** [comment]
Not sure what to suggest at this point, @khassel ?

**Comment by khassel** [comment]
Not sure about his problem, the docker setup for mm and mmpm is already included in the folder `~/magicmirror/run`. You have to replace the content of `docker-compose.yml` with the content of `rpi_mmpm.yml` and restart the container(s). Should work out of the box.

**Comment by Wolfieeewolf** [comment]
I can get MMPM to install fine. I have followed your directions to the letter but when I change the URL from /home/node/magicmirror to /home/pi/magicmirror, it will give me a bad gateway and will not install modules or the log will say they are installed but it has not actually downloaded anything. I have left the URL /home/node/magicmirror and it still will not install the modules. 

When I go to look at the config files it says they do not exist and it then creates 3 folders in the /home/pi/magicmirror folder. config, css and modules.  I believe it should be using the /home/pi/mounts/modules folder to get config and module information but for some reason, I just can't get it to work.

I have tried to install the modules manually but NPM is not installed. I have installed this to get the modules to work but again problems. Seems no matter what I do nothing will allow me to install the modules correctly.  My only option at the moment is to install magic mirror as normal and not as a docker file and then install MMPM and see if that works.

I am a little rusty on my Pi knowledge but believe I am doing everything correctly as per the instructions. I'm sure it is something I am doing that is stuffing it up as it appears everyone else can get it to work fine. I'll give it a fresh image and try again. If not I'll do it the old-fashioned way and see if I can get it to work.

**Comment by Wolfieeewolf** [comment]
I get this error code after changing the environment values 

Error Code: 502
Message: Http failure response for http://192.168.0.25:7890/api/packages/update: 502 Bad Gateway

my environment values are 

"MMPM_MAGICMIRROR_ROOT": "/home/pi/magicmirror",
  "MMPM_MAGICMIRROR_URI": "http://192.168.0.25:8080",
  "MMPM_MAGICMIRROR_PM2_PROCESS_NAME": "",
  "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": "",
  "MMPM_IS_DOCKER_IMAGE": true

I have also tried 

"MMPM_MAGICMIRROR_ROOT": "/home/node/magicmirror",
  "MMPM_MAGICMIRROR_URI": "http://192.168.0.25:8080",
  "MMPM_MAGICMIRROR_PM2_PROCESS_NAME": "",
  "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": "",
  "MMPM_IS_DOCKER_IMAGE": true

and I have tried changing "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": "", for both to

  "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": "/home/pi/magicmirror/run/docker-compse.yml",

and also   

  "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": "/home/node/magicmirror/run/docker-compse.yml",

but nothing seems to work

when installing modules I get 

Error Code: 500
Message: Http failure response for http://192.168.0.25:7890/api/packages/install: 500 INTERNAL SERVER ERROR

I don't get why it's not working but I think it has something to do with what I'm doing in this section. everything is fine up until this point

**Comment by Wolfieeewolf** [comment]
when trying to edit the config and custom.css I get

// /home/pi/magicmirror/config/config.js not found. An empty file was created for you in its place

and

/* File not found. Unable to create /home/pi/magicmirror/css/custom.css. Is the MagicMirror directory owned by root? */

I have done

 echo 'export PATH="$PATH:$HOME/.local/bin"' >> ~/.bashrc

thinking this might be the issue but still getting the same errors

I can get everything to work including the active modules tab which picks up the modules in the /home/pi/magicmirror/mounts/modules/default folder. it also picked up the MMPM module.

**Comment by Wolfieeewolf** [comment]
Soooo, I have no idea what I did but it seems to be working now.

Did a fresh install. didn't update anything which might have been an issue. Then followed the MMPM guide to install MMPM and now it seems to be working. 

The environment is set to below should anyone else have this issue. 

"MMPM_MAGICMIRROR_ROOT": "/home/node/MagicMirror",
"MMPM_MAGICMIRROR_URI": "http://192.168.0.25:8080",
"MMPM_MAGICMIRROR_PM2_PROCESS_NAME": "",
"MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": "",
"MMPM_IS_DOCKER_IMAGE": true


You're good to close this thread as the problem is solved. After all that it was a user error, I think. Don't update is the advice!!

**Comment by guysoft** [comment]
Glad you fixed it
