### ISSUE TITLE
Release status of 0.1.0

### ISSUE THREAD

**Issue by guysoft** [guysoft/MagicMirrorOS#4]
Mostly asking @khassel ,

Should we tag the current nightly as version 0.1.0 and release it? Or is there anything else you want to get out first?

**Comment by khassel** [comment]
In #3 I have to check if screensaver and wlan-power-off are disabled by default, otherwise the mirror becomes totally black after a while ...

It's up to you if you want to wait for this or if we put it in 0.2.0 ...

**Comment by guysoft** [comment]
Better wait. When #3 is fixed and tested we can release.

**Comment by guysoft** [comment]
The screensaver issue should be fixed, and there is a nightly built. I guess all that is left is to test it and release.

**Comment by khassel** [comment]
Tested the last nightly build and it works as expected. So you can make a release.

**Comment by guysoft** [comment]
Requirements? Does it work on RaspberryPi 1 2 3 or 4?

**Comment by khassel** [comment]
see https://docs.magicmirror.builders/getting-started/requirements.html

**Comment by guysoft** [comment]
Released, you are welcome to edit the release page for more information: https://github.com/guysoft/MagicMirrorOS/releases/tag/0.1.0

Then close this issue

**Comment by guysoft** [comment]
@khassel Saw you wrote "see https://docs.magicmirror.builders/getting-started/requirements.html"
Updating and closing.
