### ISSUE TITLE
Problem with installing node gyp inside docker image.

### ISSUE THREAD

**Issue by T-REX-XP** [guysoft/MagicMirrorOS#42]
Can't install addon from https://github.com/T-REX-XP/MMM-Gestures-Modern

npm i is crashing during rebuilding node-gyp 

```
gyp: Undefined variable module_path in binding.gyp while trying to load binding.gyp
```
Can you help me with finding the root cause?

Thanks

**Comment by khassel** [comment]
The docker images are based on `node:buster-slim`, so in this case `python3`, `make` and `g++` are needed but not installed.

I wrote already an [article in the faq](https://khassel.gitlab.io/magicmirror/faq/#how-to-install-os-dependencies-needed-by-a-module) how this could be solved.

Another possibility would be to additionally provide an image `karsten13/magicmirror:fat` based on `node:buster`. But the image size would be greater than 1GB (see table below) so pulling such an image would double the time for downloading.

```bash
karsten13/magicmirror   develop          f667b7d22849   28 hours ago   557MB
node                    16-buster-slim   ef157869f2fd   2 days ago     148MB
node                    16-buster        fab160ecd229   2 days ago     723MB
```

**Comment by T-REX-XP** [comment]
Fixed by adding gzip package via apt

**Comment by khassel** [comment]
The image `karsten13/magicmirror:fat` is meanwhile available (if image size doesn't matter ...).
