### ISSUE TITLE
Compliments didn't change language

### ISSUE THREAD

**Issue by Wiedenhoferkilian** [guysoft/MagicMirrorOS#43]
Hi Guys, 
This is my first time building a magic mirror and it works really great the only problem that i have is that the compliments are still in englisch and not german. I changed the language in the code and every other modul is german just not the compliments. Can someone help me?

**Comment by khassel** [comment]
There is no automatic translation of the default compliments. Here the link to [the docs](https://docs.magicmirror.builders/modules/compliments.html#default-value), you can define your own compliments in the `config.js`.

This question is unrelated to this project so I will close this issue now. If you have further questions to this please refer to the docs or ask questions related to the core project in the [forum](https://forum.magicmirror.builders/).
