### ISSUE TITLE
Unable To UnZip - Bad CRC

### ISSUE THREAD

**Issue by ryanmac8** [guysoft/MagicMirrorOS#45]
I've tried downloading the zip file from http://unofficialpi.org/Distros/MagicMirrorOS. After downloading the zip file, I'm unable to extract it. Windows and Linux is returning an error. Linux specially states it's a bad CRC (zip is corrupted).

**Comment by guysoft** [comment]
Can you provide the exact url you are.downloading?

**Comment by ryanmac8** [comment]
Tried again today and it seems to be working now so closing the issue.
