### ISSUE TITLE
Additional modules not working

### ISSUE THREAD

**Issue by auino** [guysoft/MagicMirrorOS#47]
I've tried to add additional modules to the `mounts/modules` folder, but it is not working. Also tried to access the container (`docker exec -it <container_id> bash`) to run `npm install` on the module, with no success.
I can see the module in the interface, but it's stuck at the loading phase.

Hence, is there a specific procedure to adopt in order to install new modules?

**Comment by khassel** [comment]
You already found the "specific procedure" which is doing this stuff from inside the container.

So with `docker exec -it mm bash` you are in the mm directory and then you have to navigate in the modules folder e.g. `cd modules/MMM-XYZ` and run `npm install`.

Stuck at the loading phase can be everything, error in `config.js` or modules not working out of the box (e.g. https://forum.magicmirror.builders/topic/15778/fix-for-black-screen-in-2-16-and-later).

**Comment by auino** [comment]
Thank you. I solved by rebooting the whole system. Is there a quicker way?

**Comment by khassel** [comment]
> Is there a quicker way?

see https://khassel.gitlab.io/magicmirror/installation/#start-magicmirror

**Comment by auino** [comment]
Thank you. Closing the issue.
