### ISSUE TITLE
Starting up with Debian login screen

### ISSUE THREAD

**Issue by auino** [guysoft/MagicMirrorOS#48]
The system is starting up with Debian login screen, hence, without running MM. How to solve?

**Comment by khassel** [comment]
is the container running?

can you show the logs with `docker logs mm`?

and also the logs of the start script with `cat $HOME/scripts/start.log`?

**Comment by auino** [comment]
After a reboot, the system was not correctly booting. I assume it is a disk issue.
Hence, I'm marking the issue as closed.
