### ISSUE TITLE
Add to rpi-imager

### ISSUE THREAD

**Issue by guysoft** [guysoft/MagicMirrorOS#49]
Hey, 
So I built the option to create rpi-imager json files and get MagicMirrorOS in the rpi-imager flasher utility.
We can send an OS Request at: https://github.com/raspberrypi/rpi-imager/issues
If it takes a while to get accepted, or if its not at all, I can also add it to my fork with the community maintained images at: https://github.com/guysoft/pi-imager

**Comment by guysoft** [comment]
@MichMich rpi imager needs a small 40x40 icon next to the image. Do you have any kind of logo that would work? I can squeeze the current logo and make it readable on that size. ATM using the default logo.

**Comment by MichMich** [comment]
![Icon](https://user-images.githubusercontent.com/210954/157409721-b377f649-5413-4f99-94d9-d2240e43a562.png)

Here you go!  Thanks!

**Comment by guysoft** [comment]
Cool, this is how it looks in the [unofficial imager I maintain](https://github.com/guysoft/pi-imager).
It might simplify the installation instructions on your end.
I have also submitted to rpi-imager:
https://github.com/raspberrypi/rpi-imager/issues/388
![Screenshot_20220309_134257](https://user-images.githubusercontent.com/325670/157435286-c2ad3d22-80e4-4ecf-b3e0-a39d558e4ce5.png)

**Comment by MichMich** [comment]
Cool! Feel free to add info to the docs repo as well.

**Comment by guysoft** [comment]
Done so on the main page of this repo.

I am not sure were else to include it, the getting started redirects here:
https://github.com/MichMich/MagicMirror-Documentation/blob/master/getting-started/installation.md#magicmirroros

Not sure what is the preferred method for you.

**Comment by guysoft** [comment]
This was done :)
