### ISSUE TITLE
startup scripts reference user pi

### ISSUE THREAD

**Issue by AdamLenox** [guysoft/MagicMirrorOS#64]
I built in a pi 4 using the pi imager installer this method lets you change the default user and system names. However doing so means that you hit an error saying usr/pi/scripts/check_git_repo doesn't exist. The user folder in my case is wrong (isn't pi). 

I assume this will happen with other scripts, looking at the repo shows me a few places in the config scripts that set some paths without using the $HOME variable. I assume this can be fixed. In my case I reimaged the pi since I didn't want to make all the manual changes. Figured Id at least post this in case anyone else has this problem.

**Comment by guysoft** [comment]
In other distrubutions I ran I moved all scripts to /opt/custompios or to /opt/magicmirror in this case

For example:
https://github.com/guysoft/FullPageOS/commit/73a536aa9267d3bdc9a75b934dc543b01fa31e99

The gui module is updated. So this needs to be done. I have no time atm for this id @khassel wants to do it as the maintainer
