### ISSUE TITLE
Xserver entry point script sub shell issue.

### ISSUE THREAD

**Issue by anli77** [guysoft/MagicMirrorOS#68]
Hi, 

So, using 64bit image on PI 3B+, latest as of the creation of this issue, the entrypoint.sh script for the xserver container tries to update the Xserver settings with xrandr, as a subshell: 

```
ed05cb695e20:/# cat /entrypoint.sh 
#!/bin/bash

{
  if [[ "$XRANDR_PARAMS" != "" ]]; then
    sleep 5
    xrandr $XRANDR_PARAMS
  fi
} &

/usr/bin/X :0 -nolisten tcp -s 0 -dpms vt1
```

But sub shells are done with () not curly brackets, so the xrandr call is ignored, I would also probably make the sleep command have a setting via the .env file since while x should be up and running, but if it is not then it will fail and there is no way to override it.

Also, in the README on this repo, the recommendation is to use set screen output and rotation, it is most likely easier and more compatible for different types of boards to use orientation (-o) instead:

```
ed05cb695e20:/# xrandr --help
usage: xrandr [options]
  where options are:
  --display <display> or -d <display>
  --help
  -o <normal,inverted,left,right,0,1,2,3>
            or --orientation <normal,inverted,left,right,0,1,2,3>
```

**Comment by khassel** [comment]
Thanks!

> But sub shells are done with () not curly brackets

well, maybe I was wearing the wrong glasses when I wrote that...

I built a new version of the xserver docker image, so `cd /opt/mm/run && docker compose pull && docker compose up -d` should fix that.

New variable `XRANDR_DELAY="5s"` is available, after a `cd /opt/mm && git pull` you can use it in your `.env` file.

Last thing is README, are you willing to fix this here with a PR?

**Comment by anli77** [comment]
Sure I can do a PR on the README.
