### ISSUE TITLE
No support for MMPM - the package manager for MM?

### ISSUE THREAD

**Issue by geek3dgeek** [guysoft/MagicMirrorOS#7]
No support for MMPM - the package manager for MM?

**Comment by khassel** [comment]
ah, you rely on my post [here](https://github.com/Bee-Mar/mmpm/issues/21)?

This may comes in a future release ...

**Comment by khassel** [comment]
see https://github.com/guysoft/MagicMirrorOS/issues/27#issuecomment-752212546
