### ISSUE TITLE
All docker commands say Illegal Instruction for 2024-11-19-magicmirroros-bookworm-armhf-lite-1.0.0

### ISSUE THREAD

**Issue by ROODAY** [guysoft/MagicMirrorOS#72]
I downloaded 2024-11-19-magicmirroros-bookworm-armhf-lite-1.0.0 and installed it onto my Raspberry Pi 1 B (yeah quite old), and after letting it do the install and boot up, I logged into the terminal and then tried `docker logs mm` and `docker ps -a`. I get `Illegal Instruction`, which seems to mean that the architecture docker is compiled for is wrong. `uname -m` gives me armv6l, which doesn't match armhf. Is this an issue with too old a raspberry pi? Do I have any options other than buying a new machine?

**Comment by guysoft** [comment]
Raspberrypi version 1 is not supported. I guess the readme needs to be fixed, there are two conflicting lines:
![Screenshot 2024-12-04 at 10 51 50](https://github.com/user-attachments/assets/48075cf8-a946-4b3e-8aed-2f0d306f8d9f)

The reason its failing for you is that Raspberrypi 1 uses armv6, and any raspberrypi after that uses armv7. The support for it was also dropped for Debian.
