### ISSUE TITLE
How to update the docker-mm-git-repo?

### ISSUE THREAD

**Issue by khassel** [guysoft/MagicMirrorOS#8]
@guysoft 

I think we have a gap in updating, but don't know how to handle this.

New docker images are pulled with every restart, but the docker setup is only cloned with the first install. So if there are changes in this repo (e.g. start params for mm), these are not automatically applied. This will happen rarely but then may the mm didn't start anymore.

To get such changes, a `git pull` must be done, but this may fails due to local changes done by the user. So one possibility is may to inform the user if there are new commits on the remote.
This could be checked with e.g `git remote show origin | grep "master.*out of date"`, but how can we publish this info to the user? May as text after ssh login? Any other ideas?

**Comment by guysoft** [comment]
That's a limitation you would need to handle.
You could have a ``.ENV`` file that is not put of the docker-compose.yml.
or you could decide that ``docker-compose.YML`` only gets update on new MagicMirrorOS releases. It rarely should be update.
Note also the kernel, docker, and raspbian packages don't auto-update neither. You will need to decide what automatically updates and what does not.
